### ISSUE TITLE
発表資料の内容について

### ISSUE THREAD

**Issue by tamemoto** [tamemoto/card-app#102]
3分しかないので、自身がアピールしたい部分をコメントにて(デザインも)

**Comment by manak1** [comment]
実際にzoomの背景に使ってる絵を入れたい

**Comment by kazuki-komori** [comment]
発表の時 zoom の背景に全員入れていきたいですね！

**Comment by kazuki-komori** [comment]
- ファイルの色を抽出できるところ
- tailwind を使って css 設計に悩む必要がなくなったこと

**Comment by chisakondo** [comment]
デザインはもちろん頑張ったけど、それよりデザインを忠実に再現してくれたことを言いたい

**Comment by chisakondo** [comment]
zoomの背景に全員入れたいに戦慄中
化粧するから言ってくれ…
