### ISSUE TITLE
テンプレートカードに色変更可能かどうかのchipを追加

### ISSUE THREAD

**Issue by tamemoto** [tamemoto/card-app#95]
/_template/_typeにおいて、デザインで色変更できるものだけlabel(chip)を配置したい
配置の縛りは特になし

**Comment by manak1** [comment]
![615d25467a51ddc8a61eef4461f06a08_600](https://user-images.githubusercontent.com/32151765/90316534-c3e8fc00-df5d-11ea-91e6-11a93f7c2843.jpg)
